import Pod from "./Pod";

export class Namespace {
  name!: string;
  podListByNamespace!: Pod[];
  allocatable_cpu!: number | null;
  allocatable_memory!: number | null;
  quota_request_cpu!: number;
  quota_request_memory!: number;
  current_cpu!: number;
  current_memory!: number;
  max_cpu_last2w!: number;
  max_memory_last2w!: number;
  limits_cpu!: number;
  limits_memory!: number;
  requests_cpu!: number;
  requests_memory!: number;
  percentageCurrentCpu!: number;
  percentageCurrentMemory!: number;
  percentageRequestCpu!: number;
  percentageRequestMemory!: number;
  percentageLimitCpu!: number;
  percentageLimitMemory!: number;
  displayCurrentCpu!: string;
  displayCurrentMemory!: string;
  displayRequestCpu!: string;
  displayRequestMemory!: string;
  displayLimitCpu!: string;
  displayLimitMemory!: string;
  nbrPods!: number;
  hightRequestOrMemory!: boolean;
  mediumRequestOrMemory!: boolean;
  protectedByLimits!: boolean;
  protectedByQuotas!: boolean;
  rollingUpdate!: boolean;
  container_memory_request!: number;
  container_memory_limit!: number;
  container_cpu_request!: number;
  container_cpu_limit!: number;
  newRequest_cpu!: number;
  newLimit_cpu!: number;
  newRequest_memory!: number;
  newLimit_memory!: number;
  per_newRequest_cpu!: number;
  per_newLimit_cpu!: number;
  per_newRequest_memory!: number;
  per_newLimit_memory!: number;
  nbrPodPossibleToDeploy!: number;
  nbrPodSimulation!: number;
  limitsRecommendations!: string | null;
  containsRedis!: boolean;
  team!: string;
  valueChain!: string | null;
  teamEmail!: string | null;
  percentageMaxCpu!: number;
  percentageMaxMemory!: number;
  perCpuFromCpuLimit!: string;
  perMemoryFromMemoryLimit!: string;
}
