export class Pod {
  name!: string;
  allocatable_cpu!: number | null;
  allocatable_memory!: number | null;
  quota_request_cpu!: number;
  quota_request_memory!: number;
  current_cpu!: number;
  current_memory!: number;
  max_cpu_last2w!: number;
  max_memory_last2w!: number;
  limits_cpu!: number;
  limits_memory!: number;
  requests_cpu!: number;
  requests_memory!: number;
  percentageCurrentCpu!: number;
  percentageCurrentMemory!: number;
  percentageRequestCpu!: number;
  percentageRequestMemory!: number;
  percentageLimitCpu!: number;
  percentageLimitMemory!: number;
  displayCurrentCpu!: string;
  displayCurrentMemory!: string;
  displayRequestCpu!: string;
  displayRequestMemory!: string;
  displayLimitCpu!: string;
  displayLimitMemory!: string;
  nbrPods!: number;
  hightRequestOrMemory!: boolean;
  mediumRequestOrMemory!: boolean;
  countRestart!: number;
  namespace!: string;
  appName!: string;
  terminatedReason!: string;
  container_memory_request!: number;
  container_memory_limit!: number;
  container_cpu_request!: number;
  container_cpu_limit!: number;
  cpuDisplay!: string;
  memoryDisplay!: string;
  usageCpu!: string;
  maxCpu!: string;
  usageMemory!: string;
  maxMemory!: string;
  podName!: string;
  percentageMaxCpu!: number;
  percentageMaxMemory!: number;
  perCpuFromCpuLimit!: string;
  perMemoryFromMemoryLimit!: string;
}

export default Pod;
