import { useState, useCallback } from 'react';

const useHttp = () => {
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState(null);

  const sendRequest = useCallback(async (requestConfig, applyData) => {
    setIsLoading(true);
    setError(null);
    try {
      const response = await fetch(requestConfig.url, {
        method: requestConfig.method ? requestConfig.method : 'GET',
        headers: requestConfig.headers ? requestConfig.headers : {},
        body: requestConfig.body ? JSON.stringify(requestConfig.body) : null,
      });

      if (!response.ok) {
        throw new Error('Request failed!');
      }
      console.table('in useHttp where response status is ' + response.status + ' and response is ' + response);
      const data = [
        {
          name: 'TEST worker-2.ocp-lab2.its4u.eu',
          allocatable_cpu: 9500,
          allocatable_memory: 22963,
          quota_request_cpu: 0,
          quota_request_memory: 0,
          current_cpu: 1092,
          current_memory: 7707,
          max_cpu_last2w: 0,
          max_memory_last2w: 0,
          limits_cpu: 8000,
          limits_memory: 21216,
          requests_cpu: 4584,
          requests_memory: 22854,
          percentageCurrentCpu: 11.5,
          percentageCurrentMemory: 33.6,
          percentageRequestCpu: 48.3,
          percentageRequestMemory: 99.5,
          percentageLimitCpu: 84.2,
          percentageLimitMemory: 92.4,
          displayCurrentCpu: '1092/9500',
          displayCurrentMemory: '7707/22963',
          displayRequestCpu: '4584/9500',
          displayRequestMemory: '22854/22963',
          displayLimitCpu: '8000/22963',
          displayLimitMemory: '21216/22963',
          nbrPods: 32,
          hightRequestOrMemory: true,
          mediumRequestOrMemory: true,
          percentageMaxCpu: 0.0,
          percentageMaxMemory: 0.0,
          perCpuFromCpuLimit: '14',
          perMemoryFromMemoryLimit: '36',
        },
        {
          name: ' TEST worker-5.ocp-lab2.its4u.eu',
          allocatable_cpu: 9500,
          allocatable_memory: 31027,
          quota_request_cpu: 0,
          quota_request_memory: 0,
          current_cpu: 2163,
          current_memory: 23133,
          max_cpu_last2w: 0,
          max_memory_last2w: 0,
          limits_cpu: 27050,
          limits_memory: 57926,
          requests_cpu: 8294,
          requests_memory: 24810,
          percentageCurrentCpu: 22.8,
          percentageCurrentMemory: 74.6,
          percentageRequestCpu: 87.3,
          percentageRequestMemory: 80.0,
          percentageLimitCpu: 284.7,
          percentageLimitMemory: 186.7,
          displayCurrentCpu: '2163/9500',
          displayCurrentMemory: '23133/31027',
          displayRequestCpu: '8294/9500',
          displayRequestMemory: '24810/31027',
          displayLimitCpu: '27050/31027',
          displayLimitMemory: '57926/31027',
          nbrPods: 100,
          hightRequestOrMemory: false,
          mediumRequestOrMemory: true,
          percentageMaxCpu: 0.0,
          percentageMaxMemory: 0.0,
          perCpuFromCpuLimit: '8',
          perMemoryFromMemoryLimit: '40',
        },
        {
          name: 'TEST worker-1.ocp-lab2.its4u.eu',
          allocatable_cpu: 9500,
          allocatable_memory: 22963,
          quota_request_cpu: 0,
          quota_request_memory: 0,
          current_cpu: 1226,
          current_memory: 10084,
          max_cpu_last2w: 0,
          max_memory_last2w: 0,
          limits_cpu: 8000,
          limits_memory: 21216,
          requests_cpu: 4569,
          requests_memory: 22814,
          percentageCurrentCpu: 12.9,
          percentageCurrentMemory: 43.9,
          percentageRequestCpu: 48.1,
          percentageRequestMemory: 99.4,
          percentageLimitCpu: 84.2,
          percentageLimitMemory: 92.4,
          displayCurrentCpu: '1226/9500',
          displayCurrentMemory: '10084/22963',
          displayRequestCpu: '4569/9500',
          displayRequestMemory: '22814/22963',
          displayLimitCpu: '8000/22963',
          displayLimitMemory: '21216/22963',
          nbrPods: 31,
          hightRequestOrMemory: true,
          mediumRequestOrMemory: true,
          percentageMaxCpu: 0.0,
          percentageMaxMemory: 0.0,
          perCpuFromCpuLimit: '15',
          perMemoryFromMemoryLimit: '48',
        },
        {
          name: 'TEST worker-4.ocp-lab2.its4u.eu',
          allocatable_cpu: 9500,
          allocatable_memory: 31027,
          quota_request_cpu: 0,
          quota_request_memory: 0,
          current_cpu: 1481,
          current_memory: 9839,
          max_cpu_last2w: 0,
          max_memory_last2w: 0,
          limits_cpu: 15750,
          limits_memory: 19710,
          requests_cpu: 4176,
          requests_memory: 12018,
          percentageCurrentCpu: 15.6,
          percentageCurrentMemory: 31.7,
          percentageRequestCpu: 44.0,
          percentageRequestMemory: 38.7,
          percentageLimitCpu: 165.8,
          percentageLimitMemory: 63.5,
          displayCurrentCpu: '1481/9500',
          displayCurrentMemory: '9839/31027',
          displayRequestCpu: '4176/9500',
          displayRequestMemory: '12018/31027',
          displayLimitCpu: '15750/31027',
          displayLimitMemory: '19710/31027',
          nbrPods: 51,
          hightRequestOrMemory: false,
          mediumRequestOrMemory: false,
          percentageMaxCpu: 0.0,
          percentageMaxMemory: 0.0,
          perCpuFromCpuLimit: '9',
          perMemoryFromMemoryLimit: '50',
        },
        {
          name: 'TEST worker-3.ocp-lab2.its4u.eu',
          allocatable_cpu: 9500,
          allocatable_memory: 22963,
          quota_request_cpu: 0,
          quota_request_memory: 0,
          current_cpu: 1225,
          current_memory: 11798,
          max_cpu_last2w: 0,
          max_memory_last2w: 0,
          limits_cpu: 15000,
          limits_memory: 23876,
          requests_cpu: 6594,
          requests_memory: 22576,
          percentageCurrentCpu: 12.9,
          percentageCurrentMemory: 51.4,
          percentageRequestCpu: 69.4,
          percentageRequestMemory: 98.3,
          percentageLimitCpu: 157.9,
          percentageLimitMemory: 104.0,
          displayCurrentCpu: '1225/9500',
          displayCurrentMemory: '11798/22963',
          displayRequestCpu: '6594/9500',
          displayRequestMemory: '22576/22963',
          displayLimitCpu: '15000/22963',
          displayLimitMemory: '23876/22963',
          nbrPods: 36,
          hightRequestOrMemory: true,
          mediumRequestOrMemory: true,
          percentageMaxCpu: 0.0,
          percentageMaxMemory: 0.0,
          perCpuFromCpuLimit: '8',
          perMemoryFromMemoryLimit: '49',
        },
        {
          name: 'TEST worker-0.ocp-lab2.its4u.eu',
          allocatable_cpu: 9500,
          allocatable_memory: 22963,
          quota_request_cpu: 0,
          quota_request_memory: 0,
          current_cpu: 1540,
          current_memory: 16507,
          max_cpu_last2w: 0,
          max_memory_last2w: 0,
          limits_cpu: 11000,
          limits_memory: 21316,
          requests_cpu: 6574,
          requests_memory: 21808,
          percentageCurrentCpu: 16.2,
          percentageCurrentMemory: 71.9,
          percentageRequestCpu: 69.2,
          percentageRequestMemory: 95.0,
          percentageLimitCpu: 115.8,
          percentageLimitMemory: 92.8,
          displayCurrentCpu: '1540/9500',
          displayCurrentMemory: '16507/22963',
          displayRequestCpu: '6574/9500',
          displayRequestMemory: '21808/22963',
          displayLimitCpu: '11000/22963',
          displayLimitMemory: '21316/22963',
          nbrPods: 48,
          hightRequestOrMemory: true,
          mediumRequestOrMemory: true,
          percentageMaxCpu: 0.0,
          percentageMaxMemory: 0.0,
          perCpuFromCpuLimit: '14',
          perMemoryFromMemoryLimit: '77',
        },
      ];
      console.table('in useHttp where data are : ' + data);
      applyData(data);
    } catch (err) {
      console.error(err);
    }
    setIsLoading(false);
  }, []);

  return {
    isLoading,
    error,
    sendRequest,
  };
};

export default useHttp;
